repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Run code formatting check
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Run Linter to check code style and potential issues
        entry: cargo clippy --workspace --all-targets -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false